### ISSUE TITLE
[Fix] 게임 로직 오류 수정

### ISSUE THREAD

**Issue by nheo9143** [Dr-Pong/dr_pong_game_server#27]
## Desc

- 게임 로직 오류 수정
## Detail

- 공이 바를 통과해서 나가는 경우가 발생함ㅠㅠ
## Todo
- [x] 게임 로직 오류 수정하기
- [x] 게임 시작시 게임 정보에 대한 emit 처리하기
- [x] 이미 게임을 하고 있는 유저에 대한 emit 처리하기
