### ISSUE TITLE
[Fix] 게임 렉 개선하기

### ISSUE THREAD

**Issue by nheo9143** [Dr-Pong/dr_pong_game_server#82]
## Desc

- 서버-클라이언트가 서로 다른 네트워크를 사용하는 경우 게임 렉이 심하다. 개선 작업이 필요할 것 같다.

## Detail

- 게임 렉을 발생시키는 요소들은 다음과 같은 것들이 있을 것이다
    - 과다한 setTimeOut()
        - 현재 모든 게임들이 각각의 setTimeOut()으로 돌아가기 때문에 자원의 소모가 너무 클 수 있다.
        - 한 번의 setTimeOut()으로 모든 게임을 순회한다면 성능 향상에 도움이 될 것이다.
    - 매칭 로직의 스케줄링
        - 현재 매칭을 위한 스케줄링, 게임 삭제를 위한 스케줄링 총 2개가 돌아가고 있다.
        - 매칭 로직을 외부로 분리해서 처리한다면 스케줄링 작업이 줄어들어 성능이 향상될 것이다.
    - 연산 속도
        - 실시간 게임에 필요한 대량의 연산을 수행하기에 javascript가 적절하지 않을 수 있을 것이다
        - 게임 로직을 C++로 옮기면 훨씬 나아질 것이다.

    - **서버 - 클라이언트 통신의 네트워크 레이턴시가 일정하지 않음**
        - 이게 가장 큰 문제라고 생각하는데, 게임 중 핑을 체크해본 결과 갑자기 응답이 100ms 정도 밀리는 현상이 나타나는 것을 확인할 수 있었다
        - 네트워크 통신 속도가 일정하지 않아 게임이 끊기는 느낌이 났다

## Todo
- [ ] 매칭 서버 분리하기
- [ ] setTimeOut() 로직 수정
- [x] 네트워크 통신 보완할 수 있는 로직 작성

## Etc
- 렉걸리는 영상

https://github.com/Dr-Pong/dr_pong_game_server/assets/90181905/01c18433-ebf3-46e4-abc1-1706981767b4
